<h1>Welcome to Article</h1>

<?php
/**
*  @var Mageplaza\Article\Block\ArticleDetail $block
*/

?>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

</style>

<table>
    <tr>
        <th class="article_id">Id</th>
        <th class="title">Name</th>
        <th class="content">Content</th>
        <th class="image">Image</th>
        <th class="created_at">Created at</th>
        <th class="updated_at">Update at</th>
    </tr>
    <?php

    foreach ($block->loadSpecificArticle() as $id) {  //getPostCollection xuat cac block cua table duoi dang array - du lieu di tu tren xuong duoi?>
        <tr>
            <td> <?= $id['article_id'] ?> </td>
            <td> <?= $id['title'] ?></td>
            <td> <?= $id['content']?></td>
            <td> <?= $id['image']?></td>
            <td> <?= $id['created_at']?> </td>
            <td> <?= $id['updated_at']?></td>
        </tr>
    <?php } ?>
</table>

<a href = "<?= $block->getBaseUrl()?>article/index/displayallarticles">
    <button>
        Back to list
    </button>
</a>



